name: 'Build and deploy WAR app to Azure Web App: pedrapapeltesoura9RM373282'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pedrapapeltesoura9RM373282'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_b133e8973d9a47cab2814d124a4545f5 }}
          package: '${{ github.workspace }}/target/*.war'